회원가입 기능
f-lab-edu/calorie-counter pull request #8
Opened 2022-11-30 15:21 UTC by sosnumber

- 일반사용자 회원가입
- 암호화

2022-12-01 00:58 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
브리지 패턴으로 보이는데요.
이 패턴을 쓴 이유가 뭔가요?

2022-12-01 00:59 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +    public boolean isExistId(String userId) {
항상 모든 변수에 final을 쓰는게 좋을 것 같아요.
글구 왜 써야 하는지 멘토링 시간에 이야기 나눈 것을 다시 생각해 보면 좋을것 같아요

2022-12-01 01:00 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/domain/User.java
> +@Builder @AllArgsConstructor
lombok도 좋지만
record 클래스를 써 보는것도 좋을것 같아요.

2022-12-01 01:01 UTC, f-lab-nolan commented on src/main/resources/application.properties
> +
application.properties를 거의 쓰이지 않습니다.

application.yml
을 쓰는게 좋습니다.

2022-12-01 01:02 UTC, f-lab-nolan commented on src/test/java/com/example/flabcaloriecounter/user/adapter/in/web/UserControllerTest.java
> +import static org.mockito.Mockito.*;
.* import는 좋지 않습니다.
그 이유는 뭔지도 생각을 해보는것도 좋을것 같아요

2022-12-01 01:05 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/in/web/UserController.java
> +        try {
aop를 통해 Exception을 handler 한다면 
이러한 불필요한 try 문은 필요 없어집니다.

https://ss-hoon.github.io/spring/exception_handling/
https://developjuns.tistory.com/32

참고해 보세요.

2022-12-01 01:06 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserMybatisRepository.java
> +@Component
@Service 
@Component
차이가 뭘가요?

2022-12-01 01:07 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/in/web/UserController.java
> +@RestController
@RestController
@Controller
차이가 뭘가요?

2022-12-01 01:08 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/config/MybatisConfig.java
> +@MapperScan(basePackages = "com.example.flabcaloriecounter.user.adapter.out.persistence",
Mapper 패키지가 점점 많아 질것 같은데요?
그렇다면 basePackages에 선언이 복잡해 질것 같은데요.
어떻게 하면 효율적으로 할 수 있을가요??

2022-12-01 01:11 UTC, f-lab-nolan commented on src/main/resources/mapper/UserMapper.xml
> +    <insert id="signUp" parameterType="com.example.flabcaloriecounter.user.application.port.in.response.SignUpForm" >
parameterType에 full  경로를 쓰는 것도 괜찮습니다.

Alias를 써서 사용하는 방법도 알아두었으면 합니다.

2022-12-01 01:15 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/in/web/UserController.java
> +            signUpUseCase.signUp(signUpForm);
signUpUseCase.signUp(signUpForm);
->
this.signUpUseCase.signUp(signUpForm);

이게 좀더 가독성이 좋습니다.

this를 붙이면서 지역변수인수 클래스 변수인지 판별이 됩니다.

2022-12-01 01:21 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/domain/User.java
> +@Builder @AllArgsConstructor
추가적으로 
lombok에 대해 사용해야한다 안해야한다 라고 많이들 나뉘어 집니다.
(저또한 반대주의자)

이에 Data Class를 위해서 java에서는 record class가 나왔습니다.
왜 나왔고, lombok와 record를 비교 정리하면 좋을 것 같아요

2022-12-01 01:24 UTC, f-lab-nolan commented on src/main/resources/application.properties
> +
추가적으로 local, dev , prod 환경일때는
properties의 값들이 달라집니다.

이건 어떻게 해결할건가요?

2022-12-01 02:01 UTC, sigridjineth commented on src/main/java/com/example/flabcaloriecounter/user/domain/User.java
> +@Builder @AllArgsConstructor
Lombok은 안쓰는 게 좋을 것 같아요.

2022-12-01 02:14 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/user/adapter/in/web/UserController.java
> +            signUpUseCase.signUp(signUpForm);
넵 알겠습니다!! 혹시 이 this도 컨벤션으로 적용하는부분인가요? 
아니면 모든곳에서 왠만하면 붙여주는게 좋은건가요?? 코드를보다보면 있는곳도있고, 없는곳도 있어서 질문드립니다!!

2022-12-01 02:14 UTC, sosnumber commented on src/main/resources/mapper/UserMapper.xml
> +    <insert id="signUp" parameterType="com.example.flabcaloriecounter.user.application.port.in.response.SignUpForm" >
Alias 한번 사용해보겠습니다

2022-12-01 02:16 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/user/adapter/in/web/UserController.java
> +@RestController
@RestController(@Controller내재 + 응답시 메시지바디에 데이터가 실립니다) : 요청이 오면 응답을 데이터로 반환할것이다.
@Controller : 요청이오면 응답을 HTML같은 정적파일로 반환할것이다.

2022-12-01 02:18 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserMybatisRepository.java
> +@Component
둘다 빈으로 등록이 되는것인데 @Service안에 @Component가 내재되어있고 빈으로 등록하면서 명시적으로 서비스로 인식할수있는 어노테이션으로 알고있습니다.
@Component는 컴포넌트 스캔 패키지범위 내에 @Component는 붙어있다면 스캔대상이 되어 빈 등록이됩니다

2022-12-01 02:19 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/user/adapter/in/web/UserController.java
> +        try {
공부해서 다음 피드백에 적용해보도록 하겠습니다!

2022-12-01 02:28 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/in/web/UserController.java
> +            signUpUseCase.signUp(signUpForm);
기본 java의 코딩 규칙에는 클래스 변수 인경우는 this. 을 붙이는 것으로
가이드 합니다.

보통 대부분 무시하고 넘어가는데..
가독성을 위해서라도 붙이는게 좋습니다.

2022-12-01 02:31 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/in/web/UserController.java
> +@RestController
https://mangkyu.tistory.com/49
이걸 한번 보시는게 좋을것 같아요

2022-12-01 03:07 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
UserRepository 인터페이스의 구현체들이 추가로 생긴다고해도 SignUpPort 와 연결되어있어, SignUpPort의 기능을 위임받으면서 비슷한 중복 클래스가 많이 생성되는걸 줄일수있습니다

해당클래스가 없다면 Port를 implement하면서 UserRepository를 implement하는 클래스들의 경우의 수가 많아지면서 비슷한 구조의 클래스 생성이 잦아져 중복코드, 클래스구조가 더 복잡해집니다

2022-12-01 03:14 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
현재 UserPersistenceAdapter 클래스는 SignUpPort를 implement 받았습니다.

SignUpPort를 위임받는 경우 같은 메소드를 다르게 구현하겠다는 의미인데요.

근데 이거와 UserRepository는 무슨 연관관계가 있나요?

2022-12-01 03:14 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
UserRepository를 implement를 받은거는 UserMybatisRepository 클래스입니다.

2022-12-01 03:16 UTC, sosnumber commented on src/test/java/com/example/flabcaloriecounter/user/adapter/in/web/UserControllerTest.java
> +import static org.mockito.Mockito.*;
어떤클래스들인지 명확성이 떨어지고 의도치않는 녀석도 잠재적으로 딸려올수있는 문제가 있습니다.
또한 여러 모듈로 옮기는 과정에서 단점이있다고 합니다.  
제 인텔리제이에서는 5개 이상이 import되면 자동으로 *로 변환되는것같은데 수정할수도있네요 한번 풀어놔야겠습니다.

조금 찾아보니 코틀린에선 컨벤션으로 관리하고 커밋을 못하게 할수도있는 의존성도있네요..

2022-12-01 03:17 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/user/domain/User.java
> +@Builder @AllArgsConstructor
진형님과 이야기하고 lombok은 사용해보지않기로 했는데 별도로 lombok과 record 한번 정리하겠습니다

2022-12-01 03:21 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
https://www.crocus.co.kr/1537
bridge 패턴 관련 한번 읽어보세요.

2022-12-01 03:21 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +    public boolean isExistId(String userId) {
파라미터로 넘긴값을 외부에서 수정하면 버그 발견하기가 쉽지않기때문입니다.
멘토님 제가 이부분 전에 공부하다가 궁금한점이있었는데 reference 타입같은경우 외부에서 변경하면 원본 타입에게도 영향을 주게되어 final을 붙이는것이 좋겠다고 생각했는데 primitive type같은경우도 꼭 final을 붙여야하나? 라는 생각이 들었습니다.

어떻게 지지고 볶더라도 그 메서드 스콥안에서만 변경되는값이라고 생각되어 지역변수처럼 사용되겠다 라고 생각했었는데  이것도 오류를 야기할수있나요??

2022-12-01 03:25 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +    public boolean isExistId(String userId) {
지역변수에 자꾸 값을 변경하는 방식으로
코딩을 하게 되면 오히려 로직을 읽는데 더 어렵습니다.

또한 제대로 파악이 안된 상태서 값을 변경하는 상황 발생 시
예기치 못한 오류도 범할 수 있습니다.

final변수를 쓸때는 꼭 한가지의 목적만 가지고 사용되어야 합니다.
또한 결정되는 과정이 하나의 로직이며, 그 안에서만 움직여야 오류가 줄어듭니다.

2022-12-01 04:28 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
SignUpPort 의 메소드를 구현하는 클래스가 여러개라면 각각 SignUpPort의 메소드를 구현하는코드가 중복되는것을

UserPersistenceAdapter에서 한번만 구현해도 되어 기존코드 재사용, 중복코드를 줄일수 있다.

+구현부분(repository의 구현체) 과 추상부분(UserPersistenceAdapter) 을 분리하는 장점이 있다 라고 생각하면 될까요?

저는 repository 구현체마다 port의 기능을 오버라이딩 하는부분이 중복되어 비슷한 구조의 클래스가 많아진다 라는생각만했는데 구현부분과 추상부분을 분리하는장점이있는 것이네요. 조금더 공부해보겠습니다.

2022-12-01 04:32 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
SignUpPort 의 메소드를 구현하는 클래스가 여러 개라는 상황이 어떤거 인지 알수 있을가요?

저는 repository 구현체마다 port의 기능을 오버라이딩 하는부분이 중복되어 비슷한 구조의 클래스가 많아진다 라는생각
-> 이미 비슷한 구조의 클래스가 나타나고 있지 않나요?

현재 개발된 패턴과 인터페이스를 한번 잘 봐보세요.
왜 그렇게 개발이 되어야 하는지에 대한 이유가 불명확보여요.

2022-12-01 04:33 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
추가적으로 왜 브릿지 패턴을 쓰는지에 대한 이해가 필요해 보입니다.

2022-12-01 04:54 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
> SignUpPort 의 메소드를 구현하는 클래스가 여러 개라는 상황이 어떤거 인지 알수 있을가요?
implement 받은 클래스가 여러 개라면 아마도 다른 기능을 구현하려고 한 것일텐데 이게 어떻게 기존코드 재사용, 중복코드를 줄일수 있는걸가요?

앗 죄송합니다 SignUpPort의 메소드를 구현하는 클래스가 아니고 UserRepository인데  잘못얘기한것같아요 

위와 별도로 익숙하지않은 구조인데 설계명분을 따지기보다 학습목적으로 적용하게되니.. 혼란이오는것 같습니다

구조를 이해하는데 이번주에 가장 시간이 많이 걸리는 부분이기도했습니다 ㅠㅠ

구조의 이해가 좀더 필요한 상황인것을 인지했습니다. 조금더 공부해보겠습니다!

2022-12-01 05:13 UTC, sosnumber commented on src/main/resources/application.properties
> +
yml 과 profile을 사용하여 피드백 반영을 한번 해보도록하겠습니다!!

2022-12-01 05:15 UTC, f-lab-nolan commented on src/main/resources/application.properties
> +
다음 개발 기능 피쳐에 반영해요.
제가 말한거는 이 기능과는 상관이 없으니까요

2022-12-01 05:15 UTC, f-lab-nolan approved these changes

2022-12-01 05:16 UTC, f-lab-nolan commented
추가적으로
성공일때와 실패인경우(로직 오류 던...)
파라미터가 잘못된 경우에 대해

response json을 봤으면 합니다.

2022-12-01 05:26 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/config/MybatisConfig.java
> +@MapperScan(basePackages = "com.example.flabcaloriecounter.user.adapter.out.persistence",
![image](https://user-images.githubusercontent.com/106227771/204972495-81eec32e-edb0-4d82-85ce-5651a7fc8e06.png)

공식문서를 한번 확인해 보았는데 별다른 도움될 내용이 없었고.. 패키지 범위를 좀더 넓게 잡고(com.example.flabcaloriecounter 까지만 잡는다던지..) 

@Mapper 어노테이션이 붙은 매퍼인터페이스들을 인식시켜주는 방법으로 하면 괜찮지 않을까..? 라는생각이 들긴합니다

2022-12-01 09:53 UTC, jypthemiracle requested changes
수고 많으셨어요 첫 PR 감사합니다.

2022-12-01 09:53 UTC, jypthemiracle commented on build.gradle
> +    implementation 'javax.validation:validation-api:2.0.1.Final'
javax validation은 필요 없지 않을까요? spring validation만 있으면 될 것 같은데
https://mangkyu.tistory.com/174

아 그런데 2.3부터는 기본 내장이 아니네요?

2022-12-01 09:53 UTC, jypthemiracle commented on build.gradle
> +    compileOnly 'org.projectlombok:lombok'
lombok 뺍시다

2022-12-01 09:53 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/config/MybatisConfig.java
> +            annotationClass = org.apache.ibatis.annotations.Mapper.class)
`naver-intellij-formatter` 적용 부탁드려요

2022-12-01 09:53 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/config/MybatisConfig.java
> +        sqlSessionFactoryBean.setMapperLocations(applicationContext.getResources("classpath:/mapper/*.xml"));
상수는 별도로 관리해주세요

2022-12-01 09:53 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserMapper.java
> +    boolean isExistId(String userId);
```suggestion
    boolean doesExistId(String userId);
```

2022-12-01 09:53 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserMapper.java
> +    boolean isExistId(String userId);
영문법상 안맞아요

2022-12-01 09:53 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserMybatisRepository.java
> +        SignUpForm user = SignUpForm.builder()
굳이 builder 패턴을 사용할 이유는 없을 것 같아요 생성자로 뺍시다

2022-12-01 09:53 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
저도 이건 좀 고민해보고 여기에 의견을 달겠습니다.

2022-12-01 09:53 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/application/port/in/response/SignUpForm.java
> +@NoArgsConstructor @AllArgsConstructor
멘토님 의견대로 롬복은 쓰지 맙시다!

2022-12-01 09:53 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/application/port/in/response/SignUpForm.java
> +    @Pattern(regexp = "^[a-zA-Z0-9가-힣]+$")
regexp도 별도 상수로 관리..

2022-12-01 09:53 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/application/port/out/SignUpPort.java
> +    boolean isExistId(String userId);
```suggestion
    boolean doesExistId(String userId);
```

2022-12-01 09:53 UTC, jypthemiracle commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost/calorie?serverTimezone=Asia/Seoul
dev 프로파일 따로 만들어서 외부 상수로 관리합시다

2022-12-01 09:53 UTC, jypthemiracle commented on src/test/java/com/example/flabcaloriecounter/user/adapter/in/web/UserControllerTest.java
> +@WebMvcTest(UserController.class)
MockMvc 👍

2022-12-01 09:58 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserMapper.java
> +    boolean isExistId(String userId);
java에서는 boolean이 리턴되는 경우
is 혹은 has로 보통 시작합니다.
가끔 check러 붙이는 경우가 있는데
그럴때는 리턴이 없는 void로 하며, exception을 던지는 패턴으로 씁니다.

2022-12-01 10:01 UTC, f-lab-nolan commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserMapper.java
> +    boolean isExistId(String userId);
hasMoreElement라는 메소드라는게 있습니다.
이런거 처럼
hasDuplicatedId 라는 네이밍은 어떨가요?

2022-12-01 10:06 UTC, sosnumber commented on build.gradle
> +    implementation 'javax.validation:validation-api:2.0.1.Final'
네 아마 그쯤부터 이 의존성을 뺴면 Validation이 안먹히는걸로 알고있습니다

2022-12-01 12:59 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserMapper.java
> +    boolean isExistId(String userId);
`hasDuplicatedId` 좋네요!

2022-12-01 13:41 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserPersistenceAdapter.java
> +public class UserPersistenceAdapter implements SignUpPort {
인터페이스 하나만
/v1/ api — service signature 조금씩 다름
/v2/ api — service signature 조금씩 다름

Qualifier
Service 이름 주기
* ApplicationContext -> Controller -> GetBean을 꺼내 버린다.
    * 중복이 되지 않는다. 이 클래스가 뭔지 찾아야 하는 것이 문제점.
* Application Pool에서 가져온다. DI로 받는 것이 아니라 직접 꺼내온다.
* 동적으로 꺼낸다.
* 이게 옳은가? 그냥 서비스 2개 선언하면 안되나?
    * @Autowired
    * 그러면 인터페이스는 왜 필요한 것인가?

기능을 가지고 다양하게 구현 가능하면, 기능과 구현 분리
* 그런데 웹에서 많은 경우에 기능과 구현이 함께 간다. 불필요한 것이 브릿지 패턴이다.
* Visual Studio 같은 제품
* 인텔리제이 버전업 -> 기존에 쓰던 것 중 모듈을 갈아끼고 싶다.
* Mac 호환?
아니라면 그럴 필요가 없다.

다 알고 쓰고 상황도 보아라.
이런 게 있는데, 막상 코딩을 해보니 이런 장, 단점이 있다.

2022-12-01 13:43 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/adapter/in/web/UserController.java
> +        try {
AOP를 사용해서 try-catch를 제거합시다

2022-12-01 13:51 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/user/adapter/out/persistence/UserMybatisRepository.java
> +        SignUpForm user = SignUpForm.builder()
규칙 예시
빌더패턴 — 내부적으로 만들어지는 클래스는 쓰자.
DB 엔티티의 역할 클래스는 빌더패턴을 사용하지 않는다.

2022-12-01 13:59 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/config/MybatisConfig.java
> +@MapperScan(basePackages = "com.example.flabcaloriecounter.user.adapter.out.persistence",
Mapper가 한 곳에 모여있으면 basePackages를 하나의 상위로만 선언해주면 편하다.
그러지 않으면 덜 명확하거나, 상황에 따라 구체적으로 지정해줘야 한다.

2022-12-01 14:00 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/config/MybatisConfig.java
> +@MapperScan(basePackages = "com.example.flabcaloriecounter.user.adapter.out.persistence",
다양한 패키지 구조를 시도해보면서 경험을 해보고 적정선을 찾아보는 연습을 한다.

2022-12-01 14:10 UTC, jypthemiracle commented
서비스 로직 람다 반영

2022-12-01 14:40 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/util/PasswordEncrypt.java
> +    private PasswordEncrypt() {
생성자 막으면 `new` 기본 생성, 그렇다면 private으로 받을 때와 `new` 로 받을 때는 어떤 차이?
* 빈 객체 `gc`
* `calendar` 클래스
```java
// 방법 2. (Lazy 방식)
public class Util {
  private Util() {}
  public static Util getInstance() {
    return LazyHolder.INSTANCE;
  }
  
  private static class LazyHolder {
    private static final Util INSTANCE = new Util();  
  }
}
```

2022-12-01 14:44 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/util/PasswordEncrypt.java
> +    private PasswordEncrypt() {
https://annehouse.tistory.com/389

2022-12-01 14:45 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/util/PasswordEncrypt.java
> +    private PasswordEncrypt() {
https://jpointofviewntoe.tistory.com/23

2022-12-01 16:10 UTC, sosnumber commented on src/main/java/com/example/flabcaloriecounter/config/MybatisConfig.java
> +        sqlSessionFactoryBean.setMapperLocations(applicationContext.getResources("classpath:/mapper/*.xml"));
혹시 진형님만의 상수를 관리하는 기준이 있으실까요? 
저는 특별한의미를 나타낸다거나, 자주변경이 될수있다던가, 외부에 노출, 혹은 자주사용되는경우? 분리를 했던것같은데  진형님의 의견이 궁금합니다 ㅎㅎ
개인적으로는 정답이 정해진건 아니라고 생각하긴해서.. 진형님의 생각도 같이 전달해주시면 좋을것같습니다

2022-12-05 00:51 UTC, sigridjineth commented on src/main/resources/schema.sql
> +    `withdrawalState`  enum ('withdrawal', 'notwithdrawal') default 'notwithdrawal'   NOT NULL,
우리가 지난번에 [MySQL Enum](https://velog.io/@leejh3224/%EB%B2%88%EC%97%AD-MySQL%EC%9D%98-ENUM-%ED%83%80%EC%9E%85%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-8%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0) 사용에 대해 이야기를 나눈 적이 있는데 @noah-f-lab 님의 생각이 궁금합니다.

2022-12-05 00:52 UTC, jypthemiracle commented on src/main/resources/schema.sql
> +    `withdrawalState`  enum ('withdrawal', 'notwithdrawal') default 'notwithdrawal'   NOT NULL,
우리가 지난번에 [MySQL Enum](https://velog.io/@leejh3224/%EB%B2%88%EC%97%AD-MySQL%EC%9D%98-ENUM-%ED%83%80%EC%9E%85%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-8%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0) 사용에 대해 이야기를 나눈 적이 있는데 @noah-f-lab 님의 생각이 궁금합니다.

2022-12-05 00:52 UTC, jypthemiracle commented on src/main/resources/schema.sql
> +    `withdrawalState`  enum ('withdrawal', 'notwithdrawal') default 'notwithdrawal'   NOT NULL,
저도 작은 참조 테이블을 만드는 것은 좋지 않다는 주의이긴 한데, 그 기준을 잡는 것이 다소 애매하네요.

2022-12-05 00:52 UTC, jypthemiracle approved these changes
머지하셔도 될 것 같아요.

2022-12-05 00:53 UTC, jypthemiracle commented on src/main/java/com/example/flabcaloriecounter/exception/GlobalExceptionHandler.java
> +@RestControllerAdvice
`@RestControllerAdvice` 👍

2022-12-05 00:54 UTC, f-lab-nolan commented on src/main/resources/schema.sql
> +    `withdrawalState`  enum ('withdrawal', 'notwithdrawal') default 'notwithdrawal'   NOT NULL,
> 우리가 지난번에 [MySQL Enum](https://velog.io/@leejh3224/%EB%B2%88%EC%97%AD-MySQL%EC%9D%98-ENUM-%ED%83%80%EC%9E%85%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-8%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0) 사용에 대해 이야기를 나눈 적이 있는데 @noah-f-lab 님의 생각이 궁금합니다.

이 부분은 멘토링 시간에 이야기해봐요

2022-12-05 02:58 UTC, merged